setwd("/Volumes/Transcend/PSU/STAT 380 DATA/380FinalProject")

library(data.table)
library(Metrics)
library(caret)
library(Rtsne)
library(xgboost)

library(keras)
library(tidyverse)

example<- fread("example_sub.csv")
sub_emb_train <- fread("train_model.csv")
sub_emb_test <- fread("test_model.csv")
result <- fread("tag.csv")


x.train <- xgb.DMatrix(data = as.matrix(sub_emb_train[,c(1:514)]),
					   label = as.matrix(result$tag))

#dtest <- xgb.DMatrix(sub_emb_test,missing=NA)
#===================================================================================

param <- list(objective = "multi:softprob", 
	          num_class = 10, 
			  gamma   = 0.08812012,
			  booster = "gbtree", 
			  eval_metric = "mlogloss",
			  eta = 0.09416362,
			  max_depth = 7,
			  subsample = 0.6227882,
			  colsample_bytree = 0.7387603,
			  min_child_weight = 1,
			  max_delta_step = 10
			  #tree_method = 'hist'
			  )

XGBm <- xgb.cv(params = param,nfold = 5,nthread = 6,nrounds = 180,missing = NA,data = x.train,
	           showsd = TRUE, stratified = TRUE, print_every_n = 10,early_stop_round = 20,
	           verbose = TRUE,maximize = TRUE, prediction = TRUE)

#These params are generated by loop of " the optimal parameters into xgb.train"
#https://inneka.com/ml/xgboost-in-r-how-does-xgb-cv-pass-the-optimal-parameters-into-xgb-train-2/


pred_train <- data.frame(XGBm$pred) %>% mutate(max = max.col(., ties.method = "last"), label = as.matrix(result$tag + 1))

XGBm <- xgb.train(params = param, data = x.train, nrounds = 100)

saveRDS(XGBm,'XGBm.model')

pred_test <- predict(XGBm, newdata = as.matrix(sub_emb_test))
pred_test <- as.data.frame(pred_test)
pred_test <- as.data.table(split(pred_test, 1:10))
#===================================================================================
#example<- fread("example_sub.csv")

example$subredditcars <- pred_test$`1`
example$subredditCooking <- pred_test$`2`
example$subredditMachineLearning <- pred_test$`3`
example$subredditmagicTCG <- pred_test$`4`
example$subredditpolitics <- pred_test$`5`
example$subredditReal_Estate<- pred_test$`6`
example$subredditscience <- pred_test$`7`
example$subredditStockMarket <- pred_test$`8`
example$subreddittravel <- pred_test$`9`
example$subredditvideogames <- pred_test$`10`

write.csv(example, "best_param_x.csv", row.names = FALSE)


